[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/api/*"
  to = "https://spotify-clone-api-v2.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Content-Security-Policy = """
      default-src 'self' *;
      font-src 'self' data: https: *;
      img-src 'self' data: https: *;
      media-src 'self' data: https: *;
      connect-src 'self' https://spotify-clone-api-v2.netlify.app https://api.cloudinary.com;
      style-src 'self' 'unsafe-inline' https:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
      worker-src 'self' blob:;
    """